apiVersion: blaxel.ai/v1alpha1
kind: IntegrationConnection
metadata:
  name: my-openai-integration
spec:
  integration: openai
  secret:
    apiKey: ${secrets.OPENAI_API_KEY}
---
apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  displayName: gpt-4o
  name: gpt-4o
spec:
  enabled: true
  integrationConnections:
    - my-openai-integration
  runtime:
    model: gpt-4o
    type: openai
---
apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  displayName: embedding-model-openai
  name: embedding-model-openai
spec:
  enabled: true
  integrationConnections:
    - my-openai-integration
  runtime:
    model: text-embedding-3-large
    type: openai